name: DNS Resolver

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间00:00运行

jobs:
  resolve-dns:
    runs-on: ubuntu-latest
    env:
      DOMAIN_LIST: ${{ vars.DOMAIN_LIST }}
      OUTPUT_DIR: ${{ vars.OUTPUT_DIR || 'ip_records' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create output directory
      run: mkdir -p $OUTPUT_DIR

    - name: Resolve domains and generate IP files
      run: |
        # 清空总IP文件
        : > $OUTPUT_DIR/all_ips.txt
        
        for domain in $DOMAIN_LIST; do
          # 清理域名格式
          clean_domain=$(echo "$domain" | tr -d '[:space:]')
          
          # 执行DNS解析 (使用Google DNS)
          ips=$(dig +short $clean_domain @8.8.8.8 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$')
          
          # 生成单个域名的IP文件
          echo "$ips" > "$OUTPUT_DIR/${clean_domain}.txt"
          
          # 追加到总IP文件
          echo "$ips" >> $OUTPUT_DIR/all_ips.txt
        done

        # 总IP文件去重排序
        sort -u $OUTPUT_DIR/all_ips.txt -o $OUTPUT_DIR/all_ips.txt

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add $OUTPUT_DIR/
        git commit -m "Update DNS records: $(date +'%Y-%m-%d %T')"
        git push
